apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cobank-frontend
  namespace: cobank
spec:
  hosts:
    - "*"
  gateways:
    - cobank-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: backend.cobank.svc.cluster.local
            port:
              number: 5000
    - route:
        - destination:
            host: frontend.cobank.svc.cluster.local
            port:
              number: 80
