apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "cobank-backend-k8s"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints

        # Keep only endpoints from namespace "cobank" and service "backend"
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: cobank
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: backend
          # Optional: keep only the named port "http" (or "metrics" if you name it that)
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http|metrics
