apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: cobank-backend
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/cobank-backend
    newTag: dev
  - name: cobank-frontend
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/cobank-frontend
    newTag: dev
